# Generated by Django 5.1.1 on 2024-10-13 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="slug",
            field=models.SlugField(
                blank=True,
                default=django.utils.timezone.now,
                max_length=100,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                default=django.utils.timezone.now,
                max_length=100,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True,
                default=django.utils.timezone.now,
                max_length=150,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
