# Generated by Django 5.1.1 on 2024-10-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="review",
            name="updated_at",
        ),
    ]
