# Generated by Django 5.1.1 on 2024-10-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XS", "XS"),
                    ("XXL", "XXL"),
                    ("3XL", "3XL"),
                ],
                default="M",
                max_length=100,
                null=True,
            ),
        ),
    ]
