# Generated by Django 5.1.1 on 2024-10-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_product_category_product_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.CharField(
                choices=[
                    ("MEN", "MEN"),
                    ("WOMEN", "WOMEN"),
                    ("CHILDREN", "CHILDREN"),
                    ("WATCH", "WATCH"),
                ],
                default="MEN",
                max_length=100,
            ),
        ),
    ]
