# Generated by Django 5.1.1 on 2024-10-12 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_size"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("username", "product")},
        ),
        migrations.AddField(
            model_name="review",
            name="username",
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
    ]
