# Generated by Django 5.1.1 on 2024-10-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(default=None, max_length=150),
        ),
    ]
