# Generated by Django 5.1.1 on 2024-10-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0005_category_remove_product_categories_product_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name_plural": "Brand"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={"verbose_name_plural": "Product Images"},
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={"verbose_name_plural": "Subcategories"},
        ),
    ]
