# Generated by Django 5.1.1 on 2024-10-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[("MEN", "Men"), ("WOMEN", "Women"), ("CHILDREN", "Children")],
                default="MEN",
                max_length=100,
            ),
        ),
    ]
