# Generated by Django 5.1.1 on 2024-10-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
