# Generated by Django 5.1.1 on 2024-10-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_brand_slug_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="productsImg/"
            ),
        ),
    ]
